services:
  grafana-redis:
    image: redis:7.4.1
    container_name: grafana-redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - default-network
      
  grafana-redis-exporter:
    image: oliver006/redis_exporter:v1.80.1-alpine
    container_name: grafana-redis-exporter
    restart: unless-stopped
    ports:
      - 9121:9121
    networks:
      - default-network
    environment:
      REDIS_ADDR: grafana-redis:6379

volumes:
  redis-data:

networks:
  default-network: