services:
  zlmediakit:
    image: zlmediakit/zlmediakit:master
    container_name: zlmediakit
    restart: unless-stopped
    networks:
      - default-network
    ports:
      - 80:80
      - 443:443
      - 554:554
      - 1935:1935
      - 8000:8000
      - 10000:10000
      - 3000:3000/tcp
      - 3001:3001/tcp
      - 3478:3478/udp
      - 9000:9000/udp

networks:
  default-network: