services:
  seata-server-standalone:
    container_name: seata-server-standalone
    image: apache/seata-server:2.2.0
    restart: unless-stopped
    ports:
      - 7091:7091
      - 8091:8091
    environment:
      STORE_MODE: file
      SEATA_PORT: 8091
    networks:
      - default-network

networks:
  default-network: