services:
  es-cluster-01:
    container_name: es-cluster-01
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    restart: unless-stopped
    volumes:
      - cluster-01-data:/usr/share/elasticsearch/data
    networks:
      - default-network
    ports:
      - 9200:9200
    environment:
      node.name: es-cluster-01
      cluster.name: elastic-cluster-docker
      cluster.initial_master_nodes: es-cluster-01,es-cluster-02,es-cluster-03
      discovery.seed_hosts: es-cluster-02,es-cluster-03
      bootstrap.memory_lock: true
      xpack.security.enabled: false
      xpack.license.self_generated.type: basic
      xpack.ml.use_auto_machine_memory_percent: true
      ELASTIC_PASSWORD: elastic
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9200"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s

  es-cluster-02:
    container_name: es-cluster-02
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    restart: unless-stopped
    volumes:
      - cluster-02-data:/usr/share/elasticsearch/data
    networks:
      - default-network
    ports:
      - 9300:9200
    environment:
      node.name: es-cluster-02
      cluster.name: elastic-cluster-docker
      cluster.initial_master_nodes: es-cluster-01,es-cluster-02,es-cluster-03
      discovery.seed_hosts: es-cluster-01,es-cluster-03
      bootstrap.memory_lock: true
      xpack.security.enabled: false
      xpack.license.self_generated.type: basic
      xpack.ml.use_auto_machine_memory_percent: true
      ELASTIC_PASSWORD: elastic
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9200"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s

  es-cluster-03:
    container_name: es-cluster-03
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    restart: unless-stopped
    volumes:
      - cluster-03-data:/usr/share/elasticsearch/data
    networks:
      - default-network
    ports:
      - 9400:9200
    environment:
      node.name: es-cluster-03
      cluster.name: elastic-cluster-docker
      cluster.initial_master_nodes: es-cluster-01,es-cluster-02,es-cluster-03
      discovery.seed_hosts: es-cluster-01,es-cluster-02
      bootstrap.memory_lock: true
      xpack.security.enabled: false
      xpack.license.self_generated.type: basic
      xpack.ml.use_auto_machine_memory_percent: true
      ELASTIC_PASSWORD: elastic
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9200"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s

  es-cluster-kibana:
    container_name: es-cluster-kibana
    image: docker.elastic.co/kibana/kibana:8.16.1
    restart: unless-stopped
    depends_on:
      es-cluster-01:
        condition: service_healthy
      es-cluster-02:
        condition: service_healthy
      es-cluster-03:
        condition: service_healthy
    volumes:
      - cluster-kibana-data:/usr/share/kibana/data
    networks:
      - default-network
    ports:
      - 5601:5601
    environment:
      SERVERNAME: kibana
      ELASTICSEARCH_HOSTS: '["http://es-cluster-01:9200","http://es-cluster-02:9200","http://es-cluster-03:9200"]'
      ELASTICSEARCH_USERNAME: kibana
      ELASTICSEARCH_PASSWORD: kibana
    mem_limit: 1073741824
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  es-cluster-metricbeat:
    build:
      context: ./metricbeat
      dockerfile: Dockerfile
    container_name: es-cluster-metricbeat
    restart: unless-stopped
    user: root
    depends_on:
      es-cluster-kibana:
        condition: service_healthy
    volumes:
      - cluster-metricbeat-data:/usr/share/metricbeat/data
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      ELASTIC_USER: elastic
      ELASTIC_PASSWORD: elastic
      KIBANA_HOSTS: http://es-cluster-kibana:5601
    networks:
      - default-network

  es-cluster-logstash:
    build:
      context: ./logstash
      dockerfile: Dockerfile
    container_name: es-cluster-logstash
    restart: unless-stopped
    depends_on:
      es-cluster-01:
        condition: service_healthy
      es-cluster-02:
        condition: service_healthy
      es-cluster-03:
        condition: service_healthy
    user: root
    ports:
      - 5044:5044
      - 12000:12000
    networks:
      - default-network
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xmx256m"
      LOGSTASH_INTERNAL_PASSWORD: elastic

networks:
  default-network:

volumes:
  cluster-01-data:
  cluster-02-data:
  cluster-03-data:
  cluster-kibana-data:
  cluster-metricbeat-data:
