services:
  grafana-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: grafana-elasticsearch
    restart: unless-stopped
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      node.name: grafana-elasticsearch
      cluster.name: grafana-elasticsearch
      bootstrap.memory_lock: true
      xpack.security.enabled: false
      xpack.license.self_generated.type: basic
      xpack.ml.use_auto_machine_memory_percent: true
      ELASTIC_PASSWORD: elastic
    networks:
      - default-network
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9200"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s

  grafana-elasticsearch-exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:v1.10.0
    container_name: grafana-elasticsearch-exporter
    restart: unless-stopped
    networks:
      - default-network
    depends_on:
      grafana-elasticsearch:
        condition: service_healthy
    command: |
      --es.uri=http://elastic:elastic@grafana-elasticsearch:9200
    ports:
      - 9114:9114

volumes:
  elasticsearch-data:

networks:
  default-network:
