bindAddr = "0.0.0.0"
bindPort = 7000

log.to = "console"
log.level = "info"
log.maxDays = 3
log.disablePrintColor = true

auth.method = "token"
auth.token = "12345678"

webServer.addr = "127.0.0.1"
webServer.port = 7400
webServer.user = "admin"
webServer.password = "admin"