services:
  grafana-postgres:
    image: postgres:17-alpine
    container_name: grafana-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - default-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "example", "-d", "example"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s

  grafana-postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.18.1
    container_name: grafana-postgres-exporter
    restart: unless-stopped
    depends_on:
      grafana-postgres:
        condition: service_healthy
    environment:
      - DATA_SOURCE_URI=grafana-postgres:5432/example?sslmode=disable
      - DATA_SOURCE_USER=example
      - DATA_SOURCE_PASS=example
    networks:
      - default-network
    ports:
      - 9187:9187

volumes:
  postgres-data:

networks:
  default-network:
